[pytest]
DJANGO_SETTINGS_MODULE = settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = --strict-markers --tb=short -ra
testpaths = drf_cas_jwt
markers =
    django_db: marca teste que usa DB do Django
    integration: marca testes de integração
    security: marca testes de segurança crítica
