# Generated by Django 5.2.15 on 2026-06-09 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_cas_jwt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshTokenFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, help_text='JWT ID (jti claim) do refresh token', max_length=255, unique=True)),
                ('parent_jti', models.CharField(blank=True, help_text='jti do refresh anterior (se foi rotacionado)', max_length=255, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, help_text='Data quando esse jti foi rotacionado para um novo', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Data da revogação por reuse ou outro motivo', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAlertRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email que receberá os alertas', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Desabilitar sem excluir o registro')),
                ('notify_on_reuse', models.BooleanField(default=True, help_text='Alertar quando reuse de refresh token for detectado')),
                ('notify_on_rate_limit', models.BooleanField(default=False, help_text='Alertar quando rate limit for excedido por um usuário')),
                ('notify_on_login', models.BooleanField(default=False, help_text='Alertar a cada login (útil para contas sensíveis)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destinatário de Alertas de Segurança',
                'verbose_name_plural': 'Destinatários de Alertas de Segurança',
            },
        ),
        migrations.CreateModel(
            name='TokenAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REFRESH', 'Token Refresh'), ('REFRESH_DENIED', 'Refresh Negado'), ('AUTH_DENIED', 'Autenticação Negada'), ('REUSE_DETECTED', 'Reuse de Refresh Detectado')], max_length=20)),
                ('reason', models.CharField(choices=[('invalid_token', 'Token Inválido'), ('token_reuse', 'Reuse de Token'), ('rate_limit', 'Rate Limit Excedido'), ('expired', 'Token Expirado'), ('device_mismatch', 'Device Não Corresponde'), ('success', 'Sucesso')], default='success', max_length=30)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='token',
            name='jti',
            field=models.CharField(blank=True, db_index=True, help_text='JWT ID (jti claim) para rastreamento de refresh tokens', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=64, verbose_name='Token JWT (HMAC-SHA256)'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['user', 'deleted_at'], name='drf_cas_jwt_user_id_fa0639_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['jti', 'deleted_at'], name='drf_cas_jwt_jti_fa49b4_idx'),
        ),
        migrations.AddField(
            model_name='refreshtokenfamily',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityalertrecipient',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuário Django associado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tokenauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='token',
            name='device',
        ),
        migrations.AddIndex(
            model_name='refreshtokenfamily',
            index=models.Index(fields=['user', 'revoked_at'], name='drf_cas_jwt_user_id_d623c3_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtokenfamily',
            index=models.Index(fields=['jti', 'revoked_at'], name='drf_cas_jwt_jti_814acf_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenauditlog',
            index=models.Index(fields=['user', 'created_at'], name='drf_cas_jwt_user_id_573447_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenauditlog',
            index=models.Index(fields=['event', 'created_at'], name='drf_cas_jwt_event_18fd12_idx'),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
